In [1]:
import pandas as pd

C:\Users\PERSONAL\AppData\Local\Temp\ipykernel_6824\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
seed = 42

In [3]:
csv_route = 'D:/BECA NUEVA ZELANDA/2025/AUCKLAND UNIVERSITY/ENROLED COURSES/MONITORING SPACE/DATA FINAL PROJECT/Github_project/Dataset'

In [4]:
# ...existing code...
df = pd.concat([pd.read_csv(csv_route + '/' + i) for i in ['landslides_with_variables2.csv']])
# ...existing code...

In [5]:
df.head()

,ID,Valid Landslide,Latitude,Longitude,CURVATURE,TWI,SLOPE_deg,DEM,SLOPE_deg.1,ASPECT_deg,LANDCOVER_CODE,ASPECT_rad,ASPECT_sin,ASPECT_cos,SLOPE_rad
0,1,1,-36.819859,174.746298,1.379645,5.286413,11.441814,18.809872,11.441814,222.978638,1.0,3.891711,-0.681726,-0.731608,0.199697
1,2,1,-36.798134,174.684934,0.190541,6.555068,14.671361,19.514647,14.671361,166.090866,1.0,2.898832,0.240383,-0.970678,0.256064
2,3,1,-36.932751,174.744548,0.068507,9.921234,17.020342,22.542194,17.020342,158.192902,11.0,2.760987,0.371483,-0.928440,0.297061
3,4,1,-36.852885,174.792092,0.528753,3.760681,29.180260,24.194622,29.180260,59.103947,11.0,1.031558,0.858100,0.513482,0.509292
4,5,1,-36.809204,174.718141,-0.087607,5.854521,15.388130,69.367027,15.388130,57.325916,1.0,1.000526,0.841755,0.539860,0.268574

In [6]:
df.describe()

,ID,Valid Landslide,Latitude,Longitude,CURVATURE,TWI,SLOPE_deg,DEM,SLOPE_deg.1,ASPECT_deg,LANDCOVER_CODE,ASPECT_rad,ASPECT_sin,ASPECT_cos,SLOPE_rad
count,23852.000000,23852.00000,23852.000000,23852.000000,18879.000000,18425.000000,18790.000000,18879.000000,18790.000000,18425.000000,19367.000000,18425.000000,18425.000000,18425.000000,18790.000000
mean,11926.500000,0.50000,-36.732796,174.685288,-0.014642,5.946082,16.706932,76.507340,16.706932,174.220822,4.610678,3.040727,0.063180,0.117150,0.291591
std,6885.623646,0.50001,0.217277,0.166457,0.750381,2.030337,12.299937,57.134842,12.299937,111.114309,3.171055,1.939311,0.700041,0.701627,0.214674
min,1.000000,0.00000,-37.251611,174.232113,-12.202140,1.781748,0.000000,0.409632,0.000000,0.015391,1.000000,0.000269,-1.000000,-1.000000,0.000000
25%,5963.750000,0.00000,-36.915672,174.571445,-0.199679,4.570182,5.031713,36.055607,5.031713,75.024963,2.000000,1.309433,-0.631448,-0.568355,0.087820
50%,11926.500000,0.50000,-36.754442,174.668742,0.000000,5.447597,16.136251,63.300785,16.136251,162.185944,4.000000,2.830679,0.123486,0.231115,0.281631
75%,17889.250000,1.00000,-36.542334,174.797723,0.187282,6.959876,26.028730,103.201462,26.028730,281.493713,4.000000,4.912992,0.754778,0.802324,0.454287
max,23852.000000,1.00000,-36.160394,175.277764,6.936145,20.738850,63.980480,396.625671,63.980480,359.993591,26.000000,6.283073,1.000000,1.000000,1.116670

In [7]:
df.isna().sum().to_frame('NA_Count')

                 NA_Count
ID                      0
Valid Landslide         0
Latitude                0
Longitude               0
CURVATURE            4973
TWI                  5427
SLOPE_deg            5062
DEM                  4973
SLOPE_deg.1          5062
ASPECT_deg           5427
LANDCOVER_CODE       4485
ASPECT_rad           5427
ASPECT_sin           5427
ASPECT_cos           5427
SLOPE_rad            5062

In [8]:
df = df.dropna()

In [9]:
df.isna().sum().to_frame('NA_Count')

                 NA_Count
ID                      0
Valid Landslide         0
Latitude                0
Longitude               0
CURVATURE               0
TWI                     0
SLOPE_deg               0
DEM                     0
SLOPE_deg.1             0
ASPECT_deg              0
LANDCOVER_CODE          0
ASPECT_rad              0
ASPECT_sin              0
ASPECT_cos              0
SLOPE_rad               0

In [10]:
df.describe()

,ID,Valid Landslide,Latitude,Longitude,CURVATURE,TWI,SLOPE_deg,DEM,SLOPE_deg.1,ASPECT_deg,LANDCOVER_CODE,ASPECT_rad,ASPECT_sin,ASPECT_cos,SLOPE_rad
count,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000
mean,10295.429409,0.637193,-36.702153,174.655402,-0.001590,5.946212,17.037971,77.771939,17.037971,174.226384,4.593117,3.040824,0.063123,0.117204,0.297369
std,6637.857258,0.480823,0.227076,0.169085,0.705379,2.030397,12.192384,57.141314,12.192384,111.118048,3.175827,1.939376,0.700046,0.701618,0.212797
min,1.000000,0.000000,-37.251611,174.232113,-9.351087,1.781748,0.000318,0.781750,0.000318,0.015391,1.000000,0.000269,-1.000000,-1.000000,0.000006
25%,4752.500000,0.000000,-36.902959,174.532509,-0.202104,4.570304,5.496008,37.575230,5.496008,75.019241,2.000000,1.309333,-0.631517,-0.568331,0.095923
50%,9394.000000,1.000000,-36.712489,174.626871,0.000966,5.448114,16.533924,65.211143,16.533924,162.185944,4.000000,2.830679,0.123460,0.231437,0.288571
75%,15562.500000,1.000000,-36.508717,174.731766,0.197542,6.959927,26.220399,104.908981,26.220399,281.506531,4.000000,4.913216,0.754756,0.802326,0.457632
max,23852.000000,1.000000,-36.160394,175.277764,6.936145,20.738850,63.980480,396.625671,63.980480,359.993591,26.000000,6.283073,1.000000,1.000000,1.116670

In [11]:
# Remove columns from the dataframe by specifying their names in a list
columns_to_remove = ['SLOPE_deg.1','ASPECT_rad', 'ASPECT_sin', 'ASPECT_cos', 'SLOPE_rad']
df = df.drop(columns=columns_to_remove)

In [12]:
df.describe()

,ID,Valid Landslide,Latitude,Longitude,CURVATURE,TWI,SLOPE_deg,DEM,ASPECT_deg,LANDCOVER_CODE
count,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000,18423.000000
mean,10295.429409,0.637193,-36.702153,174.655402,-0.001590,5.946212,17.037971,77.771939,174.226384,4.593117
std,6637.857258,0.480823,0.227076,0.169085,0.705379,2.030397,12.192384,57.141314,111.118048,3.175827
min,1.000000,0.000000,-37.251611,174.232113,-9.351087,1.781748,0.000318,0.781750,0.015391,1.000000
25%,4752.500000,0.000000,-36.902959,174.532509,-0.202104,4.570304,5.496008,37.575230,75.019241,2.000000
50%,9394.000000,1.000000,-36.712489,174.626871,0.000966,5.448114,16.533924,65.211143,162.185944,4.000000
75%,15562.500000,1.000000,-36.508717,174.731766,0.197542,6.959927,26.220399,104.908981,281.506531,4.000000
max,23852.000000,1.000000,-36.160394,175.277764,6.936145,20.738850,63.980480,396.625671,359.993591,26.000000

In [13]:
df.to_csv(csv_route + '/landslides_cleaned.csv', index=False)